const express =require('express')
const app =express()
const mongoose =require('mongoose')
app.use(express.urlencoded())
app.use(express.json())
app.use('/',require('./routs'))
app.set("view engine","ejs")
app.set("views","view")
app.use(express.static('./public'))
app.listen(3005,async()=>{
    await mongoose.connect('mongodb://localhost/apiwebtechassignmentAroc')
    console.log('db connect')
    console.log('port up')
})